spring:
  application:
    name: eSnack24AdminAPI
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://snackdb.chm9rhbwy6vo.ap-northeast-2.rds.amazonaws.com:3306/snackdb
    username: snackdbuser
    password: snackdbuser

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 40MB
      location: C:\\snack\\demo
      enabled: true

org:
  zerock:
    accessTime: 5
    refreshTime: 10080
    alwaysNew: true
    upload:
      path: upload

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

logging:
  level:
    org.springframework.security.web: TRACE
    org.springframework.web.multipart: DEBUG
